apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app }}-cronjob
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
          containers:
            - name: {{ .Values.cronJob.name }}
              image: {{ .Values.cronJob.image }}
              {{- if .Values.cronJob.command }}
              command:
                {{- toYaml .Values.cronJob.command | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: {{ .Values.persistentVolumeClaim.name }}
                  mountPath: {{ .Values.persistentVolume.mountPath }}
          volumes:
            - name: {{ .Values.persistentVolumeClaim.name }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistentVolumeClaim.name }}
