apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  storageClassName: {{ .Values.persistentVolume.storageClass | quote }}
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
    {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}

  {{- if .Values.persistentVolume.hostPath }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
  {{- end }}
