apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    {{- include "quake-watch-app.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  accessModes:
    {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  {{- if .Values.persistentVolume.hostPath }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
  {{- end }}
