name: Promote Dev to QA

on:
  workflow_dispatch:     # Manual trigger
  pull_request:
    types: [closed]  # Trigger after PR merged into main
    branches:
      - main

jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: main
          target_branch: qa
          title: Automatic pull request
          body: "**Automated pull request**"
          new_string: "** Automatic pull request**"
